apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - name: playground
      image: quay.io/hukhan/dsp-toolbox:latest
      command: ["sleep", "infinity"]
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /data
          name: toolbox-storage
  volumes:
    - name: toolbox-storage
      persistentVolumeClaim:
        claimName: toolbox-storage
